version: '3.1'

services:
  db:
    container_name: db
    image: postgres:14
    restart: always
    user: postgres
    command: postgres -c 'max_connections=20'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "relayer"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: relayer
    volumes:
      - ./.db:/var/lib/postgresql/data
